#
# Module manifest for module 'PSGet_GA-AppLocker'
#
# Generated by: GA-AppLocker Team
#
# Generated on: 2/17/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GA-AppLocker.psm1'

# Version number of this module.
ModuleVersion = '1.2.84'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f1e2d3c4-b5a6-7890-1234-567890abcdef'

# Author of this module
Author = 'GA-AppLocker Team'

# Company or vendor of this module
CompanyName = 'GA-AppLocker'

# Copyright statement for this module
Copyright = '(c) 2026 GA-AppLocker Team. All rights reserved.'

# Description of the functionality provided by this module
Description = 'GA-AppLocker Dashboard - Enterprise AppLocker Policy Management for Air-Gapped Environments

Features:
- Scan Active Directory for hosts by OU
- Collect AppLocker artifacts via WinRM with tiered credential support
- Auto-generate rules using best practices (Publisher > Hash > Path)
- Create and merge policies by machine type (Workstation/Server/DC)
- Deploy to GPOs with phase-based enforcement (Audit -> Enforce)
- WPF GUI with code-behind pattern and central button dispatcher'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Modules\GA-AppLocker.Core\GA-AppLocker.Core.psd1', 
               'Modules\GA-AppLocker.Storage\GA-AppLocker.Storage.psd1', 
               'Modules\GA-AppLocker.Discovery\GA-AppLocker.Discovery.psd1', 
               'Modules\GA-AppLocker.Credentials\GA-AppLocker.Credentials.psd1', 
               'Modules\GA-AppLocker.Scanning\GA-AppLocker.Scanning.psd1', 
               'Modules\GA-AppLocker.Rules\GA-AppLocker.Rules.psd1', 
               'Modules\GA-AppLocker.Policy\GA-AppLocker.Policy.psd1', 
               'Modules\GA-AppLocker.Deployment\GA-AppLocker.Deployment.psd1', 
               'Modules\GA-AppLocker.Validation\GA-AppLocker.Validation.psd1', 
               'Modules\GA-AppLocker.Setup\GA-AppLocker.Setup.psd1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Write-AppLockerLog', 'Measure-AppLockerOperation', 
               'Export-AppLockerHealthReport', 'Get-AppLockerConfig', 
               'Set-AppLockerConfig', 'Test-Prerequisites', 'Get-AppLockerDataPath', 
               'Normalize-ArtifactRecord', 'Save-SessionState', 
               'Restore-SessionState', 'Clear-SessionState', 'Get-DomainInfo', 
               'Get-OUTree', 'Get-ComputersByOU', 'Test-MachineConnectivity', 
               'Test-PingConnectivity', 'Resolve-LdapServer', 'Get-LdapConnection', 
               'Get-LdapSearchResult', 'Get-DomainInfoViaLdap', 'Get-OUTreeViaLdap', 
               'Get-ComputersByOUViaLdap', 'Set-LdapConfiguration', 
               'Test-LdapConnection', 'New-CredentialProfile', 
               'Get-CredentialProfile', 'Get-AllCredentialProfiles', 
               'Remove-CredentialProfile', 'Test-CredentialProfile', 
               'Get-CredentialForTier', 'Get-CredentialStoragePath', 
               'Get-LocalArtifacts', 'Get-RemoteArtifacts', 'Get-AppxArtifacts', 
               'Get-AppLockerEventLogs', 'Invoke-AppLockerEventQuery', 
               'Start-ArtifactScan', 'Get-ScanResults', 'Get-DefaultScanPaths', 
               'Write-ScanLog', 'Export-ScanResults', 'New-ScheduledScan', 
               'Get-ScheduledScans', 'Remove-ScheduledScan', 
               'Set-ScheduledScanEnabled', 'Invoke-ScheduledScan', 
               'New-PublisherRule', 'New-HashRule', 'New-PathRule', 
               'ConvertFrom-Artifact', 'Get-Rule', 'Get-AllRules', 'Update-RulesGrid', 
               'Remove-Rule', 'Export-RulesToXml', 'Set-RuleStatus', 
               'Get-SuggestedGroup', 'Get-KnownVendors', 'Get-RuleTemplates', 
               'New-RulesFromTemplate', 'Get-RuleTemplateCategories', 
               'Set-BulkRuleStatus', 'Approve-TrustedVendorRules', 
               'Remove-DuplicateRules', 'Find-DuplicateRules', 
               'Find-ExistingHashRule', 'Find-ExistingPublisherRule', 
               'Invoke-BatchRuleGeneration', 'Import-RulesFromXml', 
               'Get-RuleHistory', 'Save-RuleVersion', 'Restore-RuleVersion', 
               'Compare-RuleVersions', 'Get-RuleVersionContent', 
               'Remove-RuleHistory', 'Invoke-RuleHistoryCleanup', 
               'Get-RuleStoragePath', 'Get-RuleById', 'Add-Rule', 'Update-Rule', 
               'Get-RuleCounts', 'Find-RuleByHash', 'Find-RuleByPublisher', 
               'Rebuild-RulesIndex', 'Reset-RulesIndexCache', 'Save-RulesBulk', 
               'Add-RulesToIndex', 'Get-ExistingRuleIndex', 'Remove-RulesBulk', 
               'Remove-RulesFromIndex', 'Get-BatchPreview', 
               'Update-RuleStatusInIndex', 'Start-RuleIndexWatcher', 
               'Stop-RuleIndexWatcher', 'Get-RuleIndexWatcherStatus', 
               'Set-RuleIndexWatcherDebounce', 'Invoke-RuleIndexRebuild', 
               'Remove-OrphanedRuleFiles', 'Get-RuleFromRepository', 
               'Save-RuleToRepository', 'Remove-RuleFromRepository', 
               'Find-RulesInRepository', 'Get-RuleCountsFromRepository', 
               'Invoke-RuleBatchOperation', 'Test-RuleExistsInRepository', 
               'Get-RulesFromDatabase', 'Get-RuleFromDatabase', 'Add-RuleToDatabase', 
               'Update-RuleInDatabase', 'Remove-RuleFromDatabase', 
               'Initialize-RuleDatabase', 'Get-RuleDatabasePath', 
               'Test-RuleDatabaseExists', 'New-Policy', 'Get-Policy', 
               'Get-AllPolicies', 'Get-PolicyCount', 'Update-Policy', 'Remove-Policy', 
               'Set-PolicyStatus', 'Add-RuleToPolicy', 'Remove-RuleFromPolicy', 
               'Set-PolicyTarget', 'Export-PolicyToXml', 'Test-PolicyCompliance', 
               'Compare-Policies', 'Compare-RuleProperties', 'Get-PolicyDiffReport', 
               'New-PolicySnapshot', 'Get-PolicySnapshots', 'Get-PolicySnapshot', 
               'Restore-PolicySnapshot', 'Remove-PolicySnapshot', 
               'Invoke-PolicySnapshotCleanup', 'New-DeploymentJob', 
               'Get-DeploymentJob', 'Get-AllDeploymentJobs', 'Update-DeploymentJob', 
               'Remove-DeploymentJob', 'Start-Deployment', 'Stop-Deployment', 
               'Get-DeploymentStatus', 'Test-GPOExists', 'New-AppLockerGPO', 
               'Import-PolicyToGPO', 'Get-DeploymentHistory', 
               'Test-AppLockerXmlSchema', 'Test-AppLockerRuleGuids', 
               'Test-AppLockerRuleSids', 'Test-AppLockerRuleConditions', 
               'Test-AppLockerPolicyImport', 'Invoke-AppLockerPolicyValidation', 
               'Initialize-WinRMGPO', 'Initialize-AppLockerGPOs', 
               'Initialize-ADStructure', 'Initialize-AppLockerEnvironment', 
               'Get-SetupStatus', 'Enable-WinRMGPO', 'Disable-WinRMGPO', 
               'Remove-WinRMGPO', 'Initialize-DisableWinRMGPO', 
               'Remove-DisableWinRMGPO', 'Write-AuditLog', 'Get-AuditLog', 
               'Export-AuditLog', 'Clear-AuditLog', 'Get-AuditLogPath', 
               'Get-AuditLogSummary', 'Backup-AppLockerData', 
               'Restore-AppLockerData', 'Get-BackupHistory', 'Resolve-GroupSid', 
               'Get-CachedValue', 'Set-CachedValue', 'Clear-AppLockerCache', 
               'Get-CacheStatistics', 'Test-CacheKey', 'Invoke-CacheCleanup', 
               'Register-AppLockerEvent', 'Publish-AppLockerEvent', 
               'Unregister-AppLockerEvent', 'Get-AppLockerEventHandlers', 
               'Get-AppLockerEventHistory', 'Clear-AppLockerEventHistory', 
               'Get-AppLockerStandardEvents', 'Test-ValidHash', 'Test-ValidSid', 
               'Test-ValidGuid', 'Test-ValidPath', 'Test-ValidDistinguishedName', 
               'Test-ValidHostname', 'Test-ValidCollectionType', 
               'Test-ValidRuleAction', 'Test-ValidRuleStatus', 
               'Test-ValidPolicyStatus', 'Test-ValidEnforcementMode', 
               'Test-ValidTier', 'Assert-NotNullOrEmpty', 'Assert-InRange', 
               'Assert-MatchesPattern', 'Assert-InSet', 'ConvertTo-SafeFileName', 
               'ConvertTo-SafeXmlString', 'Get-ValidValues', 
               'Start-AppLockerDashboard'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'AppLocker','Security','PolicyManagement','Windows','ActiveDirectory','GPO','WPF','Enterprise'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Version 1.0.0 - Development
============================
Phase 1: Foundation (Complete)
- Core module with logging, configuration, and prerequisites check
- Basic WPF window shell with navigation
- Session context persistence

Phase 2: AD Discovery (Complete)
- Domain info retrieval
- OU tree discovery
- Machine enumeration by OU
- Connectivity testing (ping/WinRM)

Phase 3: Credential Management (Complete)
- Tiered credential model (T0: DCs, T1: Servers, T2: Workstations)
- DPAPI-encrypted credential storage
- Credential testing against target machines
- Settings panel with credential UI

Planned:
- Phase 4: Artifact Scanning
- Phase 5: Rule Generation
- Phase 6: Policy & Deployment
- Phase 7: Polish & Testing'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

