<#
.SYNOPSIS
    Compares software inventory CSV files to find differences between machines.

.DESCRIPTION
    This script compares software inventory exports from multiple machines to identify:
    - Software present on one machine but missing from others
    - Version differences for the same software
    - Publisher/signature differences
    - Unique software per machine

    Use cases:
    - Baseline comparison (reference machine vs. targets)
    - Drift detection across fleet
    - Pre/post change comparison
    - AppLocker policy planning (identify unique software)

.PARAMETER ReferencePath
    Path to the reference/baseline CSV file (the "golden image" or standard).

.PARAMETER ComparePath
    Path(s) to CSV file(s) to compare against the reference.
    Accepts wildcards (e.g., ".\Scans\*.csv") or array of paths.

.PARAMETER OutputPath
    Path for the comparison report. Defaults to .\SoftwareComparison-{timestamp}.csv

.PARAMETER CompareBy
    Field(s) to use for comparison matching:
    - Name (default): Match by software name only
    - NameVersion: Match by name AND version
    - Hash: Match by SHA256 hash (exact file match)
    - Publisher: Match by publisher name

.PARAMETER IgnoreVersion
    Ignore version differences when comparing (only report missing/extra software).

.PARAMETER ExportFormat
    Output format: CSV (default), HTML, or Both.

.EXAMPLE
    # Compare two machines
    .\Compare-SoftwareInventory.ps1 -ReferencePath ".\PC01.csv" -ComparePath ".\PC02.csv"

.EXAMPLE
    # Compare multiple machines against a baseline
    .\Compare-SoftwareInventory.ps1 -ReferencePath ".\GoldenImage.csv" -ComparePath ".\Scans\*.csv"

.EXAMPLE
    # Compare with exact hash matching
    .\Compare-SoftwareInventory.ps1 -ReferencePath ".\Baseline.csv" -ComparePath ".\Target.csv" -CompareBy Hash

.EXAMPLE
    # Generate HTML report
    .\Compare-SoftwareInventory.ps1 -ReferencePath ".\PC01.csv" -ComparePath ".\PC02.csv" -ExportFormat HTML

.NOTES
    Input CSV should be generated by Get-InstalledSoftware.ps1
    Expected columns: Name, Version, Publisher, FilePath, SHA256Hash, ComputerName
    Author: AaronLocker Utilities
    Version: 1.0

.LINK
    Get-InstalledSoftware.ps1 - Generate software inventory CSV
#>

#==============================================================================
# PARAMETERS
#==============================================================================
[CmdletBinding()]
param(
    # Reference/baseline CSV file
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$ReferencePath,

    # Comparison CSV file(s) - supports wildcards and arrays
    [Parameter(Mandatory = $true)]
    [string[]]$ComparePath,

    # Output report path
    [string]$OutputPath,

    # Comparison method
    [ValidateSet("Name", "NameVersion", "Hash", "Publisher")]
    [string]$CompareBy = "Name",

    # Ignore version differences
    [switch]$IgnoreVersion,

    # Output format
    [ValidateSet("CSV", "HTML", "Both")]
    [string]$ExportFormat = "CSV"
)

#==============================================================================
# BANNER
#==============================================================================
Write-Host @"

================================================================================
                    Software Inventory Comparison Tool
================================================================================
  Compares software inventories to identify differences between machines.
  Useful for drift detection, baseline compliance, and AppLocker planning.
================================================================================

"@ -ForegroundColor Cyan

#==============================================================================
# LOAD REFERENCE DATA
#==============================================================================

Write-Host "Loading reference file..." -ForegroundColor Yellow
Write-Host "  Path: $ReferencePath" -ForegroundColor Gray

try {
    # Load the reference CSV
    $referenceData = Import-Csv -Path $ReferencePath -Encoding UTF8

    # Validate expected columns
    $requiredColumns = @("Name")
    $csvColumns = $referenceData[0].PSObject.Properties.Name

    foreach ($col in $requiredColumns) {
        if ($col -notin $csvColumns) {
            Write-Error "Required column '$col' not found in reference file."
            exit 1
        }
    }

    # Get reference computer name (from data or filename)
    $refComputer = if ($referenceData[0].ComputerName) {
        $referenceData[0].ComputerName | Select-Object -First 1
    } else {
        [System.IO.Path]::GetFileNameWithoutExtension($ReferencePath)
    }

    Write-Host "  Reference: $refComputer ($($referenceData.Count) items)" -ForegroundColor Green
}
catch {
    Write-Error "Failed to load reference file: $_"
    exit 1
}

#==============================================================================
# RESOLVE COMPARISON FILE PATHS (expand wildcards)
#==============================================================================

Write-Host ""
Write-Host "Resolving comparison files..." -ForegroundColor Yellow

$compareFiles = @()

foreach ($path in $ComparePath) {
    # Handle wildcards
    if ($path -match '\*|\?') {
        $resolved = Get-ChildItem -Path $path -File -ErrorAction SilentlyContinue
        $compareFiles += $resolved.FullName
    }
    elseif (Test-Path $path -PathType Leaf) {
        $compareFiles += (Resolve-Path $path).Path
    }
    else {
        Write-Warning "Path not found: $path"
    }
}

# Remove the reference file from comparison if accidentally included
$compareFiles = $compareFiles | Where-Object { $_ -ne (Resolve-Path $ReferencePath).Path }

if ($compareFiles.Count -eq 0) {
    Write-Error "No valid comparison files found."
    exit 1
}

Write-Host "  Found $($compareFiles.Count) file(s) to compare" -ForegroundColor Green

#==============================================================================
# HELPER FUNCTION: CREATE COMPARISON KEY
#==============================================================================
function Get-ComparisonKey {
    <#
    .SYNOPSIS
        Generates a comparison key based on the selected comparison method.
    #>
    param(
        [PSCustomObject]$Item,
        [string]$Method
    )

    switch ($Method) {
        "Name" {
            # Match by name only (case-insensitive)
            return $Item.Name.ToLower().Trim()
        }
        "NameVersion" {
            # Match by name AND version
            $name = $Item.Name.ToLower().Trim()
            $version = if ($Item.Version) { $Item.Version.Trim() } else { "" }
            return "$name|$version"
        }
        "Hash" {
            # Match by SHA256 hash (exact binary match)
            return if ($Item.SHA256Hash) { $Item.SHA256Hash.ToUpper() } else { "NOHASH-$($Item.Name)" }
        }
        "Publisher" {
            # Match by publisher name
            $publisher = if ($Item.Publisher) { $Item.Publisher.ToLower().Trim() } else { "unknown" }
            return $publisher
        }
    }
}

#==============================================================================
# BUILD REFERENCE LOOKUP TABLE
#==============================================================================

Write-Host ""
Write-Host "Building reference lookup table (CompareBy: $CompareBy)..." -ForegroundColor Yellow

# Create hashtable for fast lookups
$referenceLookup = @{}

foreach ($item in $referenceData) {
    $key = Get-ComparisonKey -Item $item -Method $CompareBy

    if (-not $referenceLookup.ContainsKey($key)) {
        $referenceLookup[$key] = @()
    }
    $referenceLookup[$key] += $item
}

Write-Host "  Reference unique keys: $($referenceLookup.Count)" -ForegroundColor Gray

#==============================================================================
# PROCESS EACH COMPARISON FILE
#==============================================================================

$allResults = @()
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"

foreach ($compareFile in $compareFiles) {
    Write-Host ""
    Write-Host "Comparing: $([System.IO.Path]::GetFileName($compareFile))" -ForegroundColor Cyan

    try {
        # Load comparison data
        $compareData = Import-Csv -Path $compareFile -Encoding UTF8

        # Get computer name
        $targetComputer = if ($compareData[0].ComputerName) {
            $compareData[0].ComputerName | Select-Object -First 1
        } else {
            [System.IO.Path]::GetFileNameWithoutExtension($compareFile)
        }

        Write-Host "  Target: $targetComputer ($($compareData.Count) items)" -ForegroundColor Gray

        # Build target lookup
        $targetLookup = @{}
        foreach ($item in $compareData) {
            $key = Get-ComparisonKey -Item $item -Method $CompareBy
            if (-not $targetLookup.ContainsKey($key)) {
                $targetLookup[$key] = @()
            }
            $targetLookup[$key] += $item
        }

        #----------------------------------------------------------------------
        # FIND ITEMS IN REFERENCE BUT NOT IN TARGET (MISSING)
        #----------------------------------------------------------------------
        $missingCount = 0

        foreach ($key in $referenceLookup.Keys) {
            if (-not $targetLookup.ContainsKey($key)) {
                # Item exists in reference but not in target
                foreach ($refItem in $referenceLookup[$key]) {
                    $allResults += [PSCustomObject]@{
                        ComparisonType   = "MISSING"
                        ReferencePC      = $refComputer
                        TargetPC         = $targetComputer
                        Name             = $refItem.Name
                        ReferenceVersion = $refItem.Version
                        TargetVersion    = ""
                        ReferencePublisher = $refItem.Publisher
                        TargetPublisher  = ""
                        ReferencePath    = $refItem.FilePath
                        TargetPath       = ""
                        ReferenceHash    = $refItem.SHA256Hash
                        TargetHash       = ""
                        Notes            = "Present in reference, missing from target"
                    }
                    $missingCount++
                }
            }
        }

        #----------------------------------------------------------------------
        # FIND ITEMS IN TARGET BUT NOT IN REFERENCE (EXTRA)
        #----------------------------------------------------------------------
        $extraCount = 0

        foreach ($key in $targetLookup.Keys) {
            if (-not $referenceLookup.ContainsKey($key)) {
                # Item exists in target but not in reference
                foreach ($targetItem in $targetLookup[$key]) {
                    $allResults += [PSCustomObject]@{
                        ComparisonType   = "EXTRA"
                        ReferencePC      = $refComputer
                        TargetPC         = $targetComputer
                        Name             = $targetItem.Name
                        ReferenceVersion = ""
                        TargetVersion    = $targetItem.Version
                        ReferencePublisher = ""
                        TargetPublisher  = $targetItem.Publisher
                        ReferencePath    = ""
                        TargetPath       = $targetItem.FilePath
                        ReferenceHash    = ""
                        TargetHash       = $targetItem.SHA256Hash
                        Notes            = "Present in target, not in reference"
                    }
                    $extraCount++
                }
            }
        }

        #----------------------------------------------------------------------
        # FIND VERSION DIFFERENCES (if not ignoring versions)
        #----------------------------------------------------------------------
        $versionDiffCount = 0

        if (-not $IgnoreVersion -and $CompareBy -eq "Name") {
            foreach ($key in $referenceLookup.Keys) {
                if ($targetLookup.ContainsKey($key)) {
                    $refItem = $referenceLookup[$key][0]
                    $targetItem = $targetLookup[$key][0]

                    # Compare versions
                    if ($refItem.Version -ne $targetItem.Version) {
                        $allResults += [PSCustomObject]@{
                            ComparisonType   = "VERSION_DIFF"
                            ReferencePC      = $refComputer
                            TargetPC         = $targetComputer
                            Name             = $refItem.Name
                            ReferenceVersion = $refItem.Version
                            TargetVersion    = $targetItem.Version
                            ReferencePublisher = $refItem.Publisher
                            TargetPublisher  = $targetItem.Publisher
                            ReferencePath    = $refItem.FilePath
                            TargetPath       = $targetItem.FilePath
                            ReferenceHash    = $refItem.SHA256Hash
                            TargetHash       = $targetItem.SHA256Hash
                            Notes            = "Version mismatch"
                        }
                        $versionDiffCount++
                    }
                }
            }
        }

        #----------------------------------------------------------------------
        # SUMMARY FOR THIS COMPARISON
        #----------------------------------------------------------------------
        Write-Host "  Results:" -ForegroundColor Gray
        Write-Host "    Missing from target: $missingCount" -ForegroundColor $(if($missingCount -gt 0){"Yellow"}else{"Green"})
        Write-Host "    Extra on target:     $extraCount" -ForegroundColor $(if($extraCount -gt 0){"Yellow"}else{"Green"})
        if (-not $IgnoreVersion -and $CompareBy -eq "Name") {
            Write-Host "    Version differences: $versionDiffCount" -ForegroundColor $(if($versionDiffCount -gt 0){"Yellow"}else{"Green"})
        }
    }
    catch {
        Write-Warning "Failed to process $compareFile : $_"
    }
}

#==============================================================================
# EXPORT RESULTS
#==============================================================================

Write-Host ""
Write-Host "Exporting comparison results..." -ForegroundColor Yellow

# Generate output path if not specified
if (-not $OutputPath) {
    $OutputPath = ".\SoftwareComparison-$timestamp"
}

# Remove extension from output path for multi-format support
$basePath = [System.IO.Path]::ChangeExtension($OutputPath, $null).TrimEnd('.')

#------------------------------------------------------------------------------
# CSV EXPORT
#------------------------------------------------------------------------------
if ($ExportFormat -in @("CSV", "Both")) {
    $csvPath = "$basePath.csv"

    try {
        $allResults | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
        Write-Host "  CSV: $csvPath" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to export CSV: $_"
    }
}

#------------------------------------------------------------------------------
# HTML EXPORT
#------------------------------------------------------------------------------
if ($ExportFormat -in @("HTML", "Both")) {
    $htmlPath = "$basePath.html"

    try {
        # Build HTML report
        $html = @"
<!DOCTYPE html>
<html>
<head>
    <title>Software Inventory Comparison Report</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        h1 { color: #333; border-bottom: 2px solid #0078d4; padding-bottom: 10px; }
        h2 { color: #0078d4; margin-top: 30px; }
        .summary { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }
        .summary-item { display: inline-block; margin-right: 30px; }
        .summary-count { font-size: 24px; font-weight: bold; }
        .missing { color: #d83b01; }
        .extra { color: #107c10; }
        .version { color: #8764b8; }
        table { border-collapse: collapse; width: 100%; background: white; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        th { background: #0078d4; color: white; padding: 12px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:hover { background: #f0f0f0; }
        .type-MISSING { background: #fde7e9; }
        .type-EXTRA { background: #dff6dd; }
        .type-VERSION_DIFF { background: #e8daef; }
        .timestamp { color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>Software Inventory Comparison Report</h1>
    <p class="timestamp">Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>

    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-item">
            <div class="summary-count missing">$($allResults | Where-Object {$_.ComparisonType -eq "MISSING"} | Measure-Object | Select-Object -ExpandProperty Count)</div>
            <div>Missing</div>
        </div>
        <div class="summary-item">
            <div class="summary-count extra">$($allResults | Where-Object {$_.ComparisonType -eq "EXTRA"} | Measure-Object | Select-Object -ExpandProperty Count)</div>
            <div>Extra</div>
        </div>
        <div class="summary-item">
            <div class="summary-count version">$($allResults | Where-Object {$_.ComparisonType -eq "VERSION_DIFF"} | Measure-Object | Select-Object -ExpandProperty Count)</div>
            <div>Version Diff</div>
        </div>
    </div>

    <h2>Detailed Results</h2>
    <table>
        <tr>
            <th>Type</th>
            <th>Software Name</th>
            <th>Reference</th>
            <th>Target</th>
            <th>Ref Version</th>
            <th>Target Version</th>
            <th>Notes</th>
        </tr>
"@

        foreach ($result in ($allResults | Sort-Object ComparisonType, Name)) {
            $html += @"
        <tr class="type-$($result.ComparisonType)">
            <td>$($result.ComparisonType)</td>
            <td>$([System.Web.HttpUtility]::HtmlEncode($result.Name))</td>
            <td>$($result.ReferencePC)</td>
            <td>$($result.TargetPC)</td>
            <td>$([System.Web.HttpUtility]::HtmlEncode($result.ReferenceVersion))</td>
            <td>$([System.Web.HttpUtility]::HtmlEncode($result.TargetVersion))</td>
            <td>$($result.Notes)</td>
        </tr>
"@
        }

        $html += @"
    </table>
</body>
</html>
"@

        $html | Out-File -FilePath $htmlPath -Encoding UTF8
        Write-Host "  HTML: $htmlPath" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to export HTML: $_"
    }
}

#==============================================================================
# FINAL SUMMARY
#==============================================================================

Write-Host ""
Write-Host "================================================================================" -ForegroundColor Green
Write-Host "  COMPARISON COMPLETE" -ForegroundColor Green
Write-Host "================================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Total differences found: $($allResults.Count)" -ForegroundColor Cyan
Write-Host ""

# Group by type
$summary = $allResults | Group-Object ComparisonType

foreach ($group in $summary) {
    $color = switch ($group.Name) {
        "MISSING" { "Yellow" }
        "EXTRA" { "Cyan" }
        "VERSION_DIFF" { "Magenta" }
        default { "Gray" }
    }
    Write-Host "    $($group.Name): $($group.Count)" -ForegroundColor $color
}

Write-Host ""
Write-Host "  Comparison method: $CompareBy" -ForegroundColor Gray
Write-Host "  Reference file: $ReferencePath" -ForegroundColor Gray
Write-Host "  Compared against: $($compareFiles.Count) file(s)" -ForegroundColor Gray
Write-Host ""
Write-Host "================================================================================" -ForegroundColor Gray

#==============================================================================
# RETURN OUTPUT PATH
#==============================================================================
return $basePath
