#
# Module manifest for module 'PSGet_GA-AppLocker.Validation'
#
# Generated by: GA-AppLocker Team
#
# Generated on: 2/17/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GA-AppLocker.Validation.psm1'

# Version number of this module.
ModuleVersion = '1.2.84'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b7c8d9e0-f1a2-3456-7890-bcdef1234567'

# Author of this module
Author = 'GA-AppLocker Team'

# Company or vendor of this module
CompanyName = 'GA-AppLocker'

# Copyright statement for this module
Copyright = '(c) 2026 GA-AppLocker. All rights reserved.'

# Description of the functionality provided by this module
Description = 'AppLocker policy XML validation for GA-AppLocker Dashboard. Validates schema, GUIDs, SIDs, rule conditions, and live import readiness.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Test-AppLockerXmlSchema', 'Test-AppLockerRuleGuids', 
               'Test-AppLockerRuleSids', 'Test-AppLockerRuleConditions', 
               'Test-AppLockerPolicyImport', 'Invoke-AppLockerPolicyValidation'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'AppLocker','Validation','Security','Policy','XML'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Version 1.0.0:
- Initial release
- Test-AppLockerXmlSchema: Validates XML structure, collection types, enforcement modes
- Test-AppLockerRuleGuids: GUID format (uppercase), uniqueness checks
- Test-AppLockerRuleSids: SID format validation, well-known SID resolution
- Test-AppLockerRuleConditions: Publisher, Hash, Path condition validation
- Test-AppLockerPolicyImport: Live import test via Test-AppLockerPolicy cmdlet
- Invoke-AppLockerPolicyValidation: Full 5-stage validation pipeline with reporting'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

